eureka/eureka_project/Sudoku/urls.py
from django.urls import path
from . import views

app_name = "Sudoku"

urlpatterns = [
    path("", views.index, name="index"),
    path("game/<int:game_id>/", views.game_detail, name="game_detail"),
    path("complete_sudoku/", views.complete_sudoku, name="complete_sudoku"),
]

eureka/eureka_project/eureka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("regine", include("regine.urls")),
    path("Sudoku/", include("Sudoku.urls")),
]

eureka/eureka_project/home/urls.py
from django.urls import path, include
from . import views

app_name = "home"  # Define the app namespace

urlpatterns = [
    path("", views.login_view, name="login"),
    path("index/", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("difficolta", views.difficolta, name="difficolta"),
    path("categorie", views.categorie, name="categorie"),
    path(
        "set_difficoltà/<str:difficulty>/", views.set_difficolta, name="set_difficolta"
    ),
    path("game_detail/<int:game_id>/", views.game_detail, name="game_detail"),
    path("profile/", views.user_profile, name="user_profile"),
    path("filtro_giochi/", views.filtro_giochi, name="filtro_giochi"),
    path(
        "filtro_categorie/<str:game_type>/",
        views.filtro_categorie,
        name="filtro_categorie",
    ),
]

eureka/eureka_project/Sudoku/models.py
from django.db import models

# Create your models here.

eureka/eureka_project/Sudoku/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from home.models import GameBoard, CustomUser
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request):
    difficulty = request.session.get("difficulty", None)

    context = {
        "difficulty": difficulty,
    }
    return render(request, "Sudoku/index.html", context)


def game_detail(request, game_id):
    game = get_object_or_404(GameBoard, id=game_id)
    context = {"game": game}
    return render(request, "Sudoku/game_detail.html", context)


@csrf_exempt
@login_required
@require_POST
def complete_sudoku(request):
    game_id = request.POST.get("game_id")
    user = request.user
    print(f"Completato gioco {game_id} per l'utente {user}")
    game_board = get_object_or_404(GameBoard, id=game_id)
    user_profile = get_object_or_404(CustomUser, id=user.id)

    if game_board not in user_profile.completed_games.all():
        print(f"punteggio prima: {user_profile.total_score}")
        user_profile.completed_games.add(game_board)
        print(f"punteggio gioco: {game_board.value_points}")
        user_profile.save()
    print(f"Punteggio aggiornato a {user_profile.total_score}")
    return redirect("home:user_profile")

eureka/eureka_project/Sudoku/templates/Sudoku/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> prova
        </title>
        <link href="{% static 'Sudoku/style.css' %}" rel="stylesheet">
        <script src="{% static 'Sudoku/Sudoku.js' %}"></script>
        
    </head>

    <body>
        {% if difficulty %}
            <h2 id="difficulty" data-difficulty="{{ difficulty }}">Difficoltà: {{ difficulty }}</h2>
        {% else %}
            <h2 id="difficulty">Difficoltà: facile</h2>
        {% endif %}
        <!-- <h2 id="Difficoltà"></h2> -->
        <a href="{% url 'home:index' %}" class="home_link"> HOME</a>
        <hr>
        <!-- tabella sudoku generata con js -->
        <div id="tabella"></div>
        <button class="reset" onclick="reset()">Reset</button>
        <button class="soluzione" onclick="soluzione()">Soluzione</button>
        <button class="verifica" onclick="verifica()">Verifica</button>
        <!-- <button class="nuovo" onclick="nuovo()" >Nuova partita</button> -->
        <!-- linea vuota per fare spazio -->
        <br>
        <!-- riga con i numeri da inserire -->
        <div id="numeri"></div>
        <!-- pulsante gomma per cancellare un numero inserito -->
        <button  class="gomma" onclick="cancella()">
            <img src="{% static 'Sudoku\images\gomma.jpg' %}" width="50">
        </button>
    </body>

   