eureka/eureka_project/eureka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("regine", include("regine.urls")),
    path("Sudoku/", include("Sudoku.urls")),
]

eureka/eureka_project/home/urls.py
from django.urls import path, include
from . import views

app_name = "home"  # Define the app namespace

urlpatterns = [
    path("", views.login_view, name="login"),
    path("index/", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("difficolta", views.difficolta, name="difficolta"),
    path("categorie", views.categorie, name="categorie"),
    path(
        "set_difficoltà/<str:difficulty>/", views.set_difficolta, name="set_difficolta"
    ),
    path("game_detail/<int:game_id>/", views.game_detail, name="game_detail"),
    path("profile/", views.user_profile, name="user_profile"),
    path("filtro_giochi/", views.filtro_giochi, name="filtro_giochi"),
    path(
        "filtro_categorie/<str:game_type>/",
        views.filtro_categorie,
        name="filtro_categorie",
    ),
]

eureka/eureka_project/home/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.utils import timezone
from django.db.models.signals import m2m_changed


class Game(models.Model):
    name = models.CharField(max_length=100)
    game_type = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class GameBoard(models.Model):
    game = models.ForeignKey(
        Game, on_delete=models.CASCADE
    )  # Add a foreign key to Game
    board_data = models.JSONField()
    difficulty = models.CharField(max_length=50)
    value_points = models.IntegerField()

    def __str__(self):
        return f"{self.game.name} - {self.difficulty}"


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        if not username:
            raise ValueError("The Username field must be set")

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.date_joined = timezone.now()
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        return self.create_user(email, username, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    total_score = models.IntegerField(default=0)
    completed_games = models.ManyToManyField(GameBoard, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return self.username


def update_total_score(sender, instance, action, **kwargs):
    if action in ["post_add", "post_remove", "post_clear"]:
        instance.total_score = sum(
            game.value_points for game in instance.completed_games.all()
        )
        instance.save()


m2m_changed.connect(update_total_score, sender=CustomUser.completed_games.through)


class Leaderboard(models.Model):
    user = models.OneToOneField(
        "CustomUser", on_delete=models.CASCADE, related_name="leaderboard_entry"
    )
    score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} - Score: {self.score}"

eureka/eureka_project/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

eureka/eureka_project/home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from .forms import CustomUserCreationForm
from django.contrib import messages
from .models import CustomUser, GameBoard


# Create your views here.
def index(request):
    top_users = CustomUser.objects.order_by("-total_score")[:3]
    users = CustomUser.objects.order_by("-total_score")[:10]
    context = {
        "users": users,
        "top_users": top_users,
    }

    return render(request, "home/index.html", context)


def set_difficolta(request, difficulty):
    request.session["difficulty"] = difficulty
    return redirect("home:filtro_giochi")


def categorie(request):
    return render(request, "home/categorie.html")


def difficolta(request):
    return render(request, "home/difficolta.html")


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("home:index")  # Redirect to home page after login
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request, "home/login.html", {"form": form})


def register_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home:index")  # Redirect to home page after registration
        else:
            messages.error(
                request, "Registration failed. Please correct the errors below."
            )
    else:
        form = CustomUserCreationForm()
    return render(request, "home/register.html", {"form": form})


def logout_view(request):
    return auth_views.LogoutView.as_view(next_page="home:login")(request)


@login_required
def user_profile(request):
    user = request.user
    # all_games = GameBoard.objects.all()
    # completed_games = user.completed_games.all()
    all_games = GameBoard.objects.all().order_by("game__game_type", "difficulty")
    completed_games = user.completed_games.all()

    context = {
        "user": user,
        "all_games": all_games,
        "completed_games": completed_games,
    }

    return render(request, "home/user_profile.html", context)


def game_detail(request, game_id):
    game_board = get_object_or_404(GameBoard, id=game_id)
    difficulty = game_board.difficulty
    game_type = game_board.game.game_type

    if game_type == "sudoku":
        return redirect("Sudoku:game_detail", game_id=game_id)
    elif game_type == "regine":
        return redirect("regine:regine_detail", difficulty=difficulty, game_id=game_id)
    else:
        return redirect("home:index")


def filtro_giochi(request):
    user = request.user
    difficulty = request.session.get("difficulty")
    if not difficulty:
        return redirect(
            "home:index"
        )  # Redirect to home page if no difficulty is set in session
    completed_games = user.completed_games.all()

    games = GameBoard.objects.filter(difficulty=difficulty).order_by(
        "game__game_type", "difficulty"
    )
    grouped_games = {}

    for game in games:
        if game.game.name not in grouped_games:
            grouped_games[game.game.name] = []
        grouped_games[game.game.name].append(game)

    context = {
        "difficulty": difficulty,
        "grouped_games": grouped_games,
        "completed_games": completed_games,
    }
    return render(request, "home/filtro_giochi.html", context)


def filtro_categorie(request, game_type):
    user = request.user
    games = GameBoard.objects.filter(game__game_type=game_type).order_by("difficulty")
    grouped_games = {"facile": [], "medio": [], "difficile": []}
    completed_games = user.completed_games.all()

    for game in games:
        if game.difficulty in grouped_games:
            grouped_games[game.difficulty].append(game)

    sorted_grouped_games = [
        (difficulty, grouped_games[difficulty])
        for difficulty in ["facile", "medio", "difficile"]
    ]

    context = {
        "game_type": game_type,
        "grouped_games": sorted_grouped_games,
        "completed_games": completed_games,
    }
    return render(request, "home/filtro_categorie.html", context)

eureka/eureka_project/home/templates/home/difficolta.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>EUREKA</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
  body{
    font-family: "Raleway", sans-serif;
    background: linear-gradient(135deg, hsl(230, 40%, 12%), hsl(230, 20%, 7%));
              background-repeat: no-repeat;
              background-attachment: fixed;
              background-size: 100% 100%;
  }
  h1,h2,h4,h5 {font-family: "Raleway", sans-serif; color: antiquewhite;}

  .w3-third img{
    margin-bottom: -6px; 
    opacity: 0.8; 
    cursor: pointer;
  }
  .w3-third img:hover{opacity: 1}

  div.polaroid {
    width: 50%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    margin-bottom: 35px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 10px;
    color:  antiquewhite;
  }
 
  img {
    width: 150px;
    height: 150px;
  }

  div.descr {
    text-align: center;
    padding: 10px ;
  }
</style>
</head>

<body class="w3-light-grey w3-content" style="max-width:1500px">
  
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-indigo w3-animate-left w3-text-white w3-collapse w3-top w3-center" style="z-index:3;width:300px;font-weight:bold" id="mySidebar"><br>
  <h3 class="w3-padding-64 w3-center"><b>EUREKA</b></h3>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-padding w3-hide-large">CLOSE</a>
  <a href="{% url 'home:categorie' %}" onclick="w3_close()" class="w3-bar-item w3-button"> CATEGORIE</a> 
  <a href="{% url 'home:index' %}" onclick="w3_close()" class="w3-bar-item w3-button"> HOME</a>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-indigo w3-xlarge w3-padding-16">
  <span class="w3-left w3-padding">EUREKA</span>
  <a href="javascript:void(0)" class="w3-right w3-button w3-white" onclick="w3_open()">☰</a>
  <h2 style="text-align:center"> Scegli la difficoltà </h2>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px">
  <h1 style="text-align:center"> Scegli la difficoltà </h1>

  <!-- Push down content on small screens --> 
  <div class="w3-hide-large" style="margin-top:83px"></div>

  <!-- Photo grid -->
  <div w3-row>    
      
      <a href="{% url 'home:set_difficolta' difficulty='facile' %}"> 
        <div class="polaroid">
        <img src="https://previews.123rf.com/images/bbbrrn/bbbrrn1907/bbbrrn190700207/126624554-la-parola-facile-scritta-con-lettere-cubo-su-fondo-di-legno.jpg" 
        alt="FACILI (max 50 EureKalcoli)" title="FACILI (max 50 EureKalcoli)" style="width:100%">
        <div class="descr">
        <p>FACILI ( 50 EureKalcoli)</p>
        </div>
        </div>
      </a> 

      <a href="{% url 'home:set_difficolta' difficulty='medio' %}"> 
        <div class="polaroid">
        <img src="https://t4.ftcdn.net/jpg/01/28/15/17/360_F_128151797_qMDbMJyvaMijFDOs98lIgbATIXyyvugb.jpg" 
        alt="INTERMEDI (max 100 EureKalcoli)" title="INTERMEDI (max 100 EureKalcoli)" style="width:100%">
        <div class="descr">
        <p>INTERMEDI ( 100 EureKalcoli)</p>
        </div>
        </div>
      </a> 
    </div>

      <a href="{% url 'home:set_difficolta' difficulty='difficile' %}">  
        <div class="polaroid">
        <img src="https://thumbs.dreamstime.com/b/difficult-text-black-red-rectangle-stamp-sign-written-259335859.jpg" 
        alt="DIFFICILI (min 200 EureKalcoli)" title="DIFFICILI (min 200 EureKalcoli)" style="width:100%">
        <div class="descr">
        <p>DIFFICILI ( 200 EureKalcoli)</p>
        </div>
        </div>
      </a> 
    </div>
  
  </div>
</div>

</div>

<script>

// Script to open and close sidebar

function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

</script>


</body>
</html>

eureka/eureka_project/home/templates/home/filtro_categorie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Games of Type: {{ game_type }}</title>
    <style>
        body {
            margin: 0;
            font: 100% / 1.5 Raleway, sans-serif;
            color: hsl(230, 100%, 95%);
            background: linear-gradient(135deg, hsl(230, 40%, 12%), hsl(230, 20%, 7%));
            height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            text-align: center;
        }
        a:link {
            color: whitesmoke;
            background-color: transparent;
            text-decoration: none;
        }
        a:hover {
            color: hotpink;
        }
        .game-section {
            margin-bottom: 50px;
            width: 80%;
            flex-direction: column;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(255, 255, 255, 0.3);
            background: rgba(255, 255, 255, 0.1);
            width: 600px; 
            margin: 0 auto; 
        }
        .game-section.facile {
            border: 2px solid green; 
            box-shadow: 0 0 15px rgba(0, 255, 0, 0.3);
            background: rgba(0, 255, 0, 0.1);
            margin-bottom: 20px; 
        }

        .game-section.medio {
            border: 2px solid yellow; 
            box-shadow: 0 0 15px rgba(255, 255, 0, 0.3);
            background: rgba(255, 255, 0, 0.1);
            margin-bottom: 20px; 
        }

        .game-section.difficile {
            border: 2px solid red; 
            box-shadow: 0 0 15px rgba(255, 0, 0, 0.3);
            background: rgba(255, 0, 0, 0.1);
            margin-bottom: 20px; 
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid hsl(230, 100%, 80%);
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: hsl(230, 40%, 20%);
        }
        .hidden-column {
            display: none;
        }
        h1, h2 {
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <h1>Games of Type: {{ game_type }}</h1>

    {% for difficulty, games in grouped_games %}
    {% if games %}
        <div class="game-section {{ difficulty }}">
            <h2>{{ difficulty|title }}</h2>
            <table>
                <thead>
                    <tr>
                        <th>Game Name</th>
                        <th class="hidden-column"></th>
                        <th class="hidden-column"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for game in games %}
                        <tr>
                            {% if game in completed_games %}
                                <td>{{ game.game.name }} - (Completed)</td>
                            {% else %}
                                <td><a href="{% url 'home:game_detail' game.id %}">{{ game.game.name }}</a></td>
                            {% endif %}
                            <td class="hidden-column"></td>
                            <td class="hidden-column"></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endfor %}
    <a href="{% url 'home:index' %}">Back to Home</a>
</body>
</html>

eureka/eureka_project/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>EUREKA</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <style>
        body {
            background: linear-gradient(135deg, hsl(230, 40%, 12%), hsl(230, 20%, 7%));
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            font-family: "Raleway", sans-serif;
        }
        .title {
            font-family: "Raleway", sans-serif;
            color: antiquewhite;
            padding-left: 2%;
            font-size: 50px;
            margin-bottom: 50px;
        }
        .leaderboard {
            color: white;
            flex-direction: column;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            border: 2px solid white;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(255, 255, 255, 0.3);
            background: rgba(255, 255, 255, 0.1);
            width: 600px; 
            margin: 0 auto; 
        }
        h1 {
            font-size: 5rem;
            font-weight: 300;
            animation: lights 5s 750ms linear infinite;
            margin: 0;
            text-align: center;
            color: hsl(230, 100%, 95%);
        }
        .container {
            display: flex;
            align-items: flex-end;
        }
        .podium__item {
            width: 150px;
            margin: 0 10px;
        }
        .podium__rank {
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 35px;
            color: #fff;
        }
        .podium__city {
            color: white;
            text-align: center;
            padding: 0 .5rem;
        }
        .podium__number {
            width: 27px;
            height: 75px;
        }
        .podium .first {
            min-height: 300px;
            background: rgb(255,215,0);
        }
        .podium .second {
            min-height: 200px;
            background: rgb(192,192,192);
        }
        .podium .third {
            min-height: 100px;
            background: rgb(205, 127, 50);
        }
        .leaderboard-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px; 
        }
        .leaderboard-table th, .leaderboard-table td {
            border: 1px solid #000;
            padding: 10px;
            text-align: left;
        }
        .leaderboard-table tr:nth-child(even) {
            background-color: hsl(230, 20%, 7%);
        }
        .leaderboard-table tr:nth-child(odd) {
            background-color: rgba(255, 255, 255, 0.1);
        }
    </style>
</head>
<body class="w3-light-grey w3-content" style="max-width:1600px">

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-indigo w3-animate-left w3-text-white w3-collapse w3-top w3-center" style="z-index:3;width:300px;font-weight:bold" id="mySidebar"><br>
    <h3 class="w3-padding-64 w3-center"><b>EUREKA</b></h3>
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-padding w3-hide-large">CLOSE</a>
    <a href="{% url 'home:categorie' %}" class="w3-bar-item w3-button">CATEGORIE</a>
    <a href="{% url 'home:difficolta' %}" onclick="w3_close()" class="w3-bar-item w3-button">DIFFICOLTÀ</a>
    <a href="{% url 'home:user_profile' %}" onclick="w3_close()" class="w3-bar-item w3-button">PROFILO</a>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-indigo w3-xlarge w3-padding-16">
    <span class="w3-left w3-padding">EUREKA</span>
    <a href="javascript:void(0)" class="w3-right w3-button w3-white" onclick="w3_open()">☰</a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:300px">

    <!-- Push down content on small screens -->
    <div class="w3-hide-large" style="margin-top:83px"></div>

    <!-- Homepage -->
    <body>
        <div class="w3-row">
            <h1>Benvenuto su Eureka</h1>
            <h1 class="title">LEADERBOARD</h1>
            <div class="leaderboard">
                <div class="container podium">
                    <div class="podium__item">
                        <p class="podium__city">{{ top_users.1.username }} - {{ top_users.1.total_score }}</p>
                        <div class="podium__rank second">2</div>
                    </div>
                    <div class="podium__item">
                        <p class="podium__city">{{ top_users.0.username }} - {{ top_users.0.total_score }}</p>
                        <div class="podium__rank first">
                            <svg class="podium__number" viewBox="0 0 27.476 75.03" xmlns="http://www.w3.org/2000/svg">
                                <g transform="matrix(1, 0, 0, 1, 214.957736, -43.117417)">
                                    <path class="st8" d="M -198.928 43.419 C -200.528 47.919 -203.528 51.819 -207.828 55.219 C -210.528 57.319 -213.028 58.819 -215.428 60.019 L -215.428 72.819 C -210.328 70.619 -205.628 67.819 -201.628 64.119 L -201.628 117.219 L -187.528 117.219 L -187.528 43.419 L -198.928 43.419 Z" style="fill: #000;"/>
                                </g>
                            </svg>
                        </div>
                    </div>
                    <div class="podium__item">
                        <p class="podium__city">{{ top_users.2.username }} - {{ top_users.2.total_score }}</p>
                        <div class="podium__rank third">3</div>
                    </div>
                </div>
                <table class="leaderboard-table">
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Username</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users|slice:"3:" %}
                            <tr>
                                <td>{{ forloop.counter0|add:4 }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.total_score }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <script>

            // Script to open and close sidebar
            
            function w3_open() {
              document.getElementById("mySidebar").style.display = "block";
              document.getElementById("myOverlay").style.display = "block";
            }
             
            function w3_close() {
              document.getElementById("mySidebar").style.display = "none";
              document.getElementById("myOverlay").style.display = "none";
            }
            
        </script>
    </body>
    </html>

eureka/eureka_project/home/templates/home/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Profile</title>
    <style>
         body {
            margin: 0;
            font: 100% / 1.5 Raleway, sans-serif;
            color: hsl(230, 100%, 95%);
            background: linear-gradient(135deg, hsl(230, 40%, 12%), hsl(230, 20%, 7%));
            height: 100vh;

        }
        #container {
            position: relative;
            width: 100%;
            display: flex;
            flex-direction: column;
            height: 100%;

        }
        #header {
            width: auto;
            height: auto;
            display: flex;
            text-align: left;
            justify-content: space-between;
            align-items: center;
            padding: 10px 40px;
            background: rgb(24, 124, 186);
            color: white;
        }
        a:link {
            color: whitesmoke;
            background-color: transparent;
            text-decoration: none;
        }
        a:hover{
            color: hotpink;
        }
        #giochi{
            padding-left: 2%;
        }
        #punteggio{
            padding-left: 2%;
            color: whitesmoke;
            font-size: 100% / 2.5 Raleway, sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border: white;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th{
            border-bottom: 1px solid #ddd;
        }
        .odd {
            background-color: hsl(230, 20%, 7%);
        }
        .even {
            background-color: rgb(31, 29, 29);
        }
        .difficulty {
            padding: 5px;
            border-radius: 5px;
            color: white;
        }
        .difficulty.easy {
            color: green;
        }
        .difficulty.medium {
            color: yellow;
        }
        .difficulty.hard {
            color: red;
        }
    </style>
</head>
<body>
    <div id="container">
        <div id="header">
            <h2>Benvenuto: {{ user.username }}</h2>
            <div id="header_pulsanti">
                <a href="{% url 'home:logout' %}">Logout</a>
                /
                <a href="{% url 'home:index' %}">Home</a>
            </div>
        </div>

        <div id="punteggio">
            <h3>Punteggio totale: {{ user.total_score }}</h3>
        </div>

        <div id="giochi">
            <h3>Lista Giochi:</h3>
            <table>
                <thead>
                    <tr>
                        <th>Game</th>
                        <th>Difficoltà</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for game in all_games %}
                        <tr class="{% cycle 'odd' 'even' %}">
                            <td>{{ game.game.name }}</td>
                            <td>
                                <span class="difficulty {% if game.difficulty == 'facile' %}easy{% elif game.difficulty == 'medio' %}medium{% elif game.difficulty == 'difficile' %}hard{% endif %}">
                                    {{ game.difficulty }}
                                </span>
                            </td>
                            <td>
                                {% if game in completed_games %}
                                    Completed
                                {% else %}
                                    <a href="{% url 'home:game_detail' game.id %}">Play</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>